In [ ]:
import numpy as np


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
a = [1,2,3.5,"4"]
arr2 = np.array(a)
print(arr2)

['1' '2' '3.5' '4']


In [ ]:
import numpy as np
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)
lr = np.array(l)
print(lr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.arange(1,21,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
import numpy as np
arr = np.zeros((3,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr = np.ones((3,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr = np.linspace(1,5,2)
print(arr)

[1. 5.]


Random Generation

In [ ]:
import numpy as np
import random

np.random.rand(10)
np.random.randn(10)
np.random.randint(1,100,3)

array([71, 10, 38])

Vector

In [ ]:
import numpy as np
arr = np.arange(11,21)
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
import numpy as np
arr = np.arange(1,31).reshape(5,6)
print(arr[3:5,1:3])
print(arr[3:,3:])
print(arr[:,3])

[[20 21]
 [26 27]]
[[22 23 24]
 [28 29 30]]
[ 4 10 16 22 28]


In [ ]:
import numpy as np
arr = np.arange(1,21)
bool_index = arr % 2 == 0
arr = arr[bool_index]
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


Array Operations

In [ ]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
a2+=a1
print(a2)
a2-=1
print(a2)
#

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[ 6  8 10 12 14]


In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a1 @ a2
np.dot(a1,a2)
#

array([[19, 22],
       [43, 50]])

Valid Sudoku

In [ ]:
import numpy as np
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
    ])
rs = np.sum(s,axis=1)
result = (rs == 45)
if result.all():
    print("Valid Sudoku")
else:
    print("Invalid Sudoku")

for i in range(0,9,3):
  for j in range(0,9,3):
    b = s[i:i+3,j:j+3]
    bs = np.sum(b)
    if bs != 45:
      print("Invalid Sudoku")
      break
    else:
      continue
else:
  print("Valid Sudoku")



Valid Sudoku
Valid Sudoku
